"""
PDF export — TASK-11I.

Generates print-friendly PDFs with the spec's required structure:
  * Cover page with audit metadata
  * Page header on every page: report type, run ID, page X of Y
  * Page footer: tenant name, "Generated by Sentinel Decision Systems"
  * Numbers formatted per TASK-11A standards
  * Rounding footnote where applicable

Two report types:
  - backtest_summary    sections 1-3 of a TASK-8 backtest (executive view)
  - calibration_only    section 3 only — model validation evidence (SR 11-7)

Reportlab's Platypus framework drives layout. Reportlab is already in
the venv (used by python-docx for an unrelated docs flow).
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Optional, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


# ────────────────────────────────────────────────────────────────────────
# Number formatting (mirrors TASK-11A frontend formatMetric)
# ────────────────────────────────────────────────────────────────────────


def _fmt_currency(value, full=False):
    if value is None:
        return "—"
    is_neg = value < 0
    abs_v = abs(value)
    if not full:
        if abs_v >= 1_000_000_000:
            s = f"${abs_v/1_000_000_000:.1f}B"
        elif abs_v >= 1_000_000:
            s = f"${abs_v/1_000_000:.1f}M"
        elif abs_v >= 10_000:
            s = f"${abs_v/1_000:.1f}K"
        else:
            s = f"${abs_v:,.0f}"
    else:
        s = f"${abs_v:,.0f}"
    return f"({s})" if is_neg else s


def _fmt_pct(value, decimals=1):
    if value is None:
        return "—"
    pct = value * 100 if abs(value) <= 1.5 else value
    return f"{pct:.{decimals}f}%"


def _fmt_count(value):
    if value is None:
        return "—"
    return f"{int(value):,}" if value >= 0 else f"({int(abs(value)):,})"


def _fmt_ratio(value, decimals=4):
    if value is None:
        return "—"
    return f"{value:.{decimals}f}"


def _fmt_dt(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    try:
        return datetime.fromisoformat(iso.replace("Z", "")).strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return iso


# ────────────────────────────────────────────────────────────────────────
# Page header / footer
# ────────────────────────────────────────────────────────────────────────


def _make_page_decorator(report_type: str, run_id: str, tenant_name: str):
    """Return a function that draws the header/footer on every page."""

    def decorator(canvas, doc):
        canvas.saveState()
        # Header
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawString(0.75 * inch, letter[1] - 0.5 * inch, report_type)
        canvas.drawRightString(
            letter[0] - 0.75 * inch, letter[1] - 0.5 * inch,
            f"Run {run_id[:8]} · Page {doc.page}",
        )
        # Footer
        canvas.drawString(0.75 * inch, 0.5 * inch, tenant_name)
        canvas.drawRightString(
            letter[0] - 0.75 * inch, 0.5 * inch,
            "Generated by Sentinel Decision Systems",
        )
        canvas.restoreState()

    return decorator


# ────────────────────────────────────────────────────────────────────────
# Cover page
# ────────────────────────────────────────────────────────────────────────


def _cover_page(
    title: str,
    subtitle: str,
    audit: dict[str, Any],
    styles,
) -> list:
    elements = []
    title_style = ParagraphStyle(
        "TitleBig", parent=styles["Heading1"], fontSize=24, leading=28,
        textColor=colors.HexColor("#0a3d62"), spaceAfter=12,
    )
    sub_style = ParagraphStyle(
        "SubTitle", parent=styles["Normal"], fontSize=11, leading=14,
        textColor=colors.grey, spaceAfter=24,
    )
    label_style = ParagraphStyle(
        "AuditLabel", parent=styles["Normal"], fontSize=9, leading=12,
        textColor=colors.grey,
    )

    elements.append(Spacer(1, 1.5 * inch))
    elements.append(Paragraph(title, title_style))
    elements.append(Paragraph(subtitle, sub_style))

    # Audit metadata table
    audit_rows = [
        ["Run ID", audit.get("run_id", "—")],
        ["Dataset", f"{audit.get('dataset_filename', '—')} ({_fmt_count(audit.get('dataset_row_count'))} rows)"],
        ["Dataset hash", audit.get("dataset_content_hash", "—")],
        ["Model", f"{audit.get('model_name', '—')} ({audit.get('model_algorithm', '—')})"],
        ["Model artifact", audit.get("model_artifact_path", "—")],
        ["Policy", audit.get("policy_label", "—")],
        ["Started", _fmt_dt(audit.get("started_at"))],
        ["Completed", _fmt_dt(audit.get("completed_at"))],
        ["Computed by", audit.get("started_by", "—")],
        ["Engine version", audit.get("engine_version", "—")],
    ]
    audit_table = Table(audit_rows, colWidths=[1.6 * inch, 5 * inch])
    audit_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]))
    elements.append(audit_table)
    elements.append(Spacer(1, 0.5 * inch))

    elements.append(Paragraph(
        "<b>Audit notice.</b> All numbers in this report are computed from "
        "the unrounded values in the source dataset. Rounding is applied "
        "only at display time. Rerunning this backtest with the same "
        "inputs produces byte-identical results (TASK-11D reproducibility "
        "guarantee).",
        label_style,
    ))
    elements.append(PageBreak())
    return elements


# ────────────────────────────────────────────────────────────────────────
# Section 1 — Execution Summary
# ────────────────────────────────────────────────────────────────────────


def _section_execution_summary(run: dict, styles) -> list:
    elements = [Paragraph("Execution Summary", styles["Heading2"])]
    rows = [
        ["Run ID", run["id"]],
        ["Status", run["status"]],
        ["Rows processed",
         f"{_fmt_count(run.get('rows_processed'))} / {_fmt_count(run.get('dataset_row_count'))}"],
        ["Errors", _fmt_count(run.get("rows_errors"))],
        ["Warnings", _fmt_count(run.get("rows_warnings"))],
        ["Avg latency / row", f"{run.get('avg_latency_ms', 0):.2f} ms"],
        ["Started", _fmt_dt(run.get("started_at"))],
        ["Completed", _fmt_dt(run.get("completed_at"))],
    ]
    t = Table(rows, colWidths=[2 * inch, 4.6 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.3 * inch))
    return elements


# ────────────────────────────────────────────────────────────────────────
# Section 2 — Decision Distribution
# ────────────────────────────────────────────────────────────────────────


def _section_decision_distribution(run: dict, styles) -> list:
    elements = [Paragraph("Decision Distribution", styles["Heading2"])]
    n_total = max((run.get("rows_processed") or 0), 1)
    n_approved = run.get("n_approved") or 0
    n_denied = run.get("n_denied") or 0
    rows = [
        ["Decision", "Count", "Share", "Total $"],
        ["Approve",
         _fmt_count(n_approved),
         _fmt_pct(n_approved / n_total),
         _fmt_currency(run.get("total_approved_dollars"))],
        ["Deny",
         _fmt_count(n_denied),
         _fmt_pct(n_denied / n_total),
         "—"],
    ]
    t = Table(rows, colWidths=[1.5 * inch, 1.5 * inch, 1.5 * inch, 2.1 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8edf3")),
        ("TEXTCOLOR", (1, 1), (-1, -1), colors.black),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(
        "<i>Total Predicted Loss $: " +
        _fmt_currency(run.get("total_predicted_loss_dollars")) + "</i>",
        styles["Normal"],
    ))
    elements.append(Spacer(1, 0.3 * inch))
    return elements


# ────────────────────────────────────────────────────────────────────────
# Section 3 — Calibration View
# ────────────────────────────────────────────────────────────────────────


def _section_calibration(run: dict, styles) -> list:
    elements = [Paragraph("Calibration View", styles["Heading2"])]
    if not run.get("has_outcomes"):
        elements.append(Paragraph(
            "<i>No outcome label detected on this dataset. Tag a target "
            "column on the dataset (TASK-6 metadata) to enable calibration "
            "analysis.</i>",
            styles["Normal"],
        ))
        return elements

    rows = [
        ["Metric", "Value", "Interpretation"],
        ["AUC", _fmt_ratio(run.get("auc")),
         "Discrimination — area under ROC; 0.5 = random, 1.0 = perfect"],
        ["KS statistic", _fmt_ratio(run.get("ks_statistic")),
         "Separation between defaulters and non-defaulters"],
        ["Brier score", _fmt_ratio(run.get("brier_score")),
         "Mean squared error of probability predictions"],
        ["Brier skill score", _fmt_ratio(run.get("brier_skill_score")),
         "Improvement over base-rate baseline; <0 means worse"],
        ["Calibration error", _fmt_pct(run.get("calibration_error_pp")),
         "|predicted mean rate − observed rate|"],
    ]
    t = Table(rows, colWidths=[1.6 * inch, 1.0 * inch, 4.0 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8edf3")),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.2 * inch))

    # Summary line per spec
    auc = run.get("auc")
    ks = run.get("ks_statistic")
    cal_err = run.get("calibration_error_pp")
    summary = (
        f"<i>AUC of {_fmt_ratio(auc)} indicates "
        f"{'strong' if auc and auc > 0.7 else 'moderate' if auc and auc > 0.6 else 'weak'} "
        f"discrimination. KS of {_fmt_ratio(ks)} measures peak separation "
        f"between defaulters and non-defaulters. Calibration error of "
        f"{_fmt_pct(cal_err)} indicates "
        f"{'good' if cal_err is not None and cal_err < 0.02 else 'moderate' if cal_err is not None and cal_err < 0.05 else 'concerning'} "
        f"alignment between predicted and observed rates.</i>"
    )
    elements.append(Paragraph(summary, styles["Normal"]))
    return elements


# ────────────────────────────────────────────────────────────────────────
# Public entry points
# ────────────────────────────────────────────────────────────────────────


def export_backtest_summary_pdf(run: dict, tenant_name: str = "Sentinel Customer") -> bytes:
    """Generate the executive backtest summary PDF (cover + sections 1-3)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.85 * inch, bottomMargin=0.85 * inch,
    )
    styles = getSampleStyleSheet()
    decorator = _make_page_decorator(
        report_type="Engine Backtest Summary",
        run_id=run["id"],
        tenant_name=tenant_name,
    )

    story = []
    story.extend(_cover_page(
        title="Engine Backtest Summary",
        subtitle="Production decisioning replayed on the input file. SR 11-7 evidence.",
        audit={
            "run_id": run.get("id"),
            "dataset_filename": run.get("dataset_filename"),
            "dataset_row_count": run.get("dataset_row_count"),
            "dataset_content_hash": run.get("dataset_content_hash"),
            "model_name": run.get("model_name") or run.get("model_id", "")[:8],
            "model_algorithm": run.get("model_algorithm"),
            "model_artifact_path": run.get("model_artifact_path"),
            "policy_label": run.get("policy_label") or run.get("policy_id", "")[:8],
            "started_at": run.get("started_at"),
            "completed_at": run.get("completed_at"),
            "started_by": run.get("started_by"),
            "engine_version": run.get("engine_version"),
        },
        styles=styles,
    ))
    story.extend(_section_execution_summary(run, styles))
    story.extend(_section_decision_distribution(run, styles))
    story.extend(_section_calibration(run, styles))

    doc.build(story, onFirstPage=decorator, onLaterPages=decorator)
    return buf.getvalue()


def export_calibration_only_pdf(run: dict, tenant_name: str = "Sentinel Customer") -> bytes:
    """Generate the calibration-only PDF — model validation evidence for
    SR 11-7 documentation. Single section, no executive overhead."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.85 * inch, bottomMargin=0.85 * inch,
    )
    styles = getSampleStyleSheet()
    decorator = _make_page_decorator(
        report_type="Calibration Evidence",
        run_id=run["id"],
        tenant_name=tenant_name,
    )

    story = []
    story.extend(_cover_page(
        title="Model Calibration Evidence",
        subtitle="SR 11-7 validation report — predicted vs. observed comparison.",
        audit={
            "run_id": run.get("id"),
            "dataset_filename": run.get("dataset_filename"),
            "dataset_row_count": run.get("dataset_row_count"),
            "dataset_content_hash": run.get("dataset_content_hash"),
            "model_name": run.get("model_name") or run.get("model_id", "")[:8],
            "model_algorithm": run.get("model_algorithm"),
            "model_artifact_path": run.get("model_artifact_path"),
            "policy_label": run.get("policy_label") or run.get("policy_id", "")[:8],
            "started_at": run.get("started_at"),
            "completed_at": run.get("completed_at"),
            "started_by": run.get("started_by"),
            "engine_version": run.get("engine_version"),
        },
        styles=styles,
    ))
    story.extend(_section_calibration(run, styles))

    doc.build(story, onFirstPage=decorator, onLaterPages=decorator)
    return buf.getvalue()
